# Generated by Django 2.2 on 2019-04-10 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='Item_name',
            new_name='Item_Description',
        ),
    ]
